-- Migration 0040: Phase E-Rx — prescription lifecycle columns.
-- These columns (cancelled_at, cancellation_reason, dispensed_at, updated_at)
-- were already added to the prescriptions table in migration 0015_keen_leopardon.sql.
-- Hence this migration is a no-op.
