#!/usr/bin/env bun
// E-Rx Phase 1: seed medicines_master + safety reference data.
//
// Reads the curated list at ./seed-rxcui-list.ts and generates a
// D1-compatible SQL file at /tmp/seed-medicines.sql, then applies it
// to D1 via `wrangler d1 execute`.
//
// Idempotent: re-runs upsert by rxcui / name. Safe to re-run.
//
// Usage (from apps/api):
//   bun run scripts/seed-medicines.ts [--remote]

import { spawnSync } from "node:child_process";
import { writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";

import {
  SEED_MEDICINES,
  SEED_INTERACTIONS,
  SEED_ALLERGY_FAMILIES,
  SEED_PREGNANCY_WARNINGS,
  SEED_RENAL_ADJUSTMENTS,
  SEED_LIVER_ADJUSTMENTS,
  SEED_CONTROLLED,
} from "./seed-rxcui-list";

// Deterministic UUID generator based on MD5 hashing of keys.
// Ensures that repeating seed runs yields the exact same UUIDs,
// completely eliminating primary key and foreign key conflicts.
function deterministicId(seed: string): string {
  const hash = createHash("md5").update(seed).digest("hex");
  return [
    hash.substring(0, 8),
    hash.substring(8, 12),
    hash.substring(12, 16),
    hash.substring(16, 20),
    hash.substring(20, 32)
  ].join("-");
}

function esc(s: string) {
  return String(s).replace(/'/g, "''");
}

const lines: string[] = [];
const out = (s: string) => lines.push(s);

out(`-- Generated by apps/api/scripts/seed-medicines.ts on ${new Date().toISOString()}`);
out(`-- Curated starter set + safety reference data. Idempotent.`);
out(``);

// ─── 1. Reference / lookup tables ──────────────────────────
out(`-- 1. Reference / lookup tables`);

// Build a small unique-name set then INSERT OR IGNORE.
function upsertRef(table: string, name: string) {
  const rowId = deterministicId(`${table}:${name.toLowerCase()}`);
  out(
    `INSERT OR IGNORE INTO ${table} (id, name) VALUES ('${rowId}', '${esc(name)}');`
  );
  return rowId;
}

const dosageFormIdByName = new Map<string, string>();
for (const m of SEED_MEDICINES) {
  if (!dosageFormIdByName.has(m.dosageForm)) {
    dosageFormIdByName.set(m.dosageForm, upsertRef("medicine_dosage_forms", m.dosageForm));
  }
}

const routeIdByName = new Map<string, string>();
for (const m of SEED_MEDICINES) {
  if (!routeIdByName.has(m.route)) {
    routeIdByName.set(m.route, upsertRef("medicine_routes", m.route));
  }
}

const categoryIdByName = new Map<string, string>();
for (const m of SEED_MEDICINES) {
  if (!categoryIdByName.has(m.category)) {
    categoryIdByName.set(m.category, upsertRef("medicine_categories", m.category));
  }
}

const atcClassIdByCode = new Map<string, string>();
for (const m of SEED_MEDICINES) {
  if (!atcClassIdByCode.has(m.atcCode)) {
    const rowId = deterministicId(`atc:${m.atcCode.toLowerCase()}`);
    out(
      `INSERT OR IGNORE INTO medicine_therapeutic_classes (id, atc_code, name) VALUES ('${rowId}', '${esc(m.atcCode)}', '${esc(m.atcName)}');`
    );
    atcClassIdByCode.set(m.atcCode, rowId);
  }
}

out(``);

// ─── 2. Master medicine rows ───────────────────────────────
out(`-- 2. Master medicine rows (medicines_master + junctions)`);

const masterIdByRxcui = new Map<string, string>();
for (const m of SEED_MEDICINES) {
  // Resolve FK ids we just upserted.
  const dosageFormId = dosageFormIdByName.get(m.dosageForm)!;
  const routeId = routeIdByName.get(m.route)!;
  const categoryId = categoryIdByName.get(m.category)!;
  const atcClassId = atcClassIdByCode.get(m.atcCode)!;
  const rowId = deterministicId(`rx:${m.rxcui}`);

  // Upsert by rxcui. Use `INSERT ... ON CONFLICT(rxcui) DO UPDATE` so
  // re-runs refresh name/strength/etc.
  const genericName = esc(m.genericName);
  const brandName = m.brandName ? `'${esc(m.brandName)}'` : "NULL";
  const strength = `'${esc(m.strength)}'`;
  const scheduleClass = `'${esc(m.scheduleClass)}'`;
  const isGeneric = m.isGeneric ? 1 : 0;
  out(
    `INSERT INTO medicines_master (id, rxcui, generic_name, brand_name, strength, dosage_form_id, route_id, category_id, atc_class_id, schedule_class, is_generic, active) ` +
      `VALUES ('${rowId}', '${esc(m.rxcui)}', '${genericName}', ${brandName}, ${strength}, '${dosageFormId}', '${routeId}', '${categoryId}', '${atcClassId}', ${scheduleClass}, ${isGeneric}, 1) ` +
      `ON CONFLICT(rxcui) DO UPDATE SET ` +
      `generic_name = excluded.generic_name, ` +
      `brand_name = excluded.brand_name, ` +
      `strength = excluded.strength, ` +
      `dosage_form_id = excluded.dosage_form_id, ` +
      `route_id = excluded.route_id, ` +
      `category_id = excluded.category_id, ` +
      `atc_class_id = excluded.atc_class_id, ` +
      `schedule_class = excluded.schedule_class, ` +
      `is_generic = excluded.is_generic, ` +
      `updated_at = CURRENT_TIMESTAMP ` +
      `RETURNING id;`
  );
  masterIdByRxcui.set(m.rxcui, rowId);

  // Insert into master ingredients junction: link the generic_name as
  // the canonical ingredient (so checkAllergy can match by generic).
  const ingredientRowId = deterministicId(`ing:${genericName.toLowerCase()}`);
  out(
    `INSERT OR IGNORE INTO medicine_ingredients (id, name) VALUES ('${ingredientRowId}', '${genericName}');`
  );
  out(
    `INSERT OR IGNORE INTO medicines_master_ingredients (medicine_id, ingredient_id, strength) VALUES ('${rowId}', '${ingredientRowId}', ${strength});`
  );

  // Link category + ATC class.
  out(
    `INSERT OR IGNORE INTO medicines_master_categories (medicine_id, category_id) VALUES ('${rowId}', '${categoryId}');`
  );
  out(
    `INSERT OR IGNORE INTO medicines_master_classes (medicine_id, class_id) VALUES ('${rowId}', '${atcClassId}');`
  );
}

out(``);

// ─── 3. Safety: drug interactions master ──────────────────
out(`-- 3. drug_interactions_master`);
for (const it of SEED_INTERACTIONS) {
  // Store pair in lowercase + sorted so (warfarin,aspirin) and
  // (aspirin,warfarin) don't double-insert.
  const [a, b] = [it.ingredientA, it.ingredientB].map((s) =>
    s.toLowerCase()
  ).sort();
  const rowId = deterministicId(`int:${a}:${b}`);
  out(
    `INSERT INTO drug_interactions_master (id, ingredient_a, ingredient_b, severity, mechanism, recommendation, source, active) ` +
      `VALUES ('${rowId}', '${esc(a)}', '${esc(b)}', '${it.severity}', '${esc(it.mechanism)}', '${esc(it.recommendation)}', 'curated', 1) ` +
      `ON CONFLICT(ingredient_a, ingredient_b) DO UPDATE SET ` +
      `severity = excluded.severity, mechanism = excluded.mechanism, recommendation = excluded.recommendation;`
  );
}

out(``);

// ─── 4. Safety: drug_allergies_master ─────────────────────
out(`-- 4. drug_allergies_master`);
for (const fam of SEED_ALLERGY_FAMILIES) {
  for (const m of fam.members) {
    const ingKey = m.ingredient.toLowerCase();
    const rowId = deterministicId(`alg:${ingKey}`);
    const cross = JSON.stringify(m.crossReactives);
    out(
      `INSERT INTO drug_allergies_master (id, ingredient_name, family, cross_reactives) ` +
        `VALUES ('${rowId}', '${esc(ingKey)}', '${esc(fam.family)}', '${esc(cross)}') ` +
        `ON CONFLICT(ingredient_name) DO UPDATE SET ` +
        `family = excluded.family, cross_reactives = excluded.cross_reactives;`
    );
  }
}

out(``);

// ─── 5. Safety: pregnancy / renal / liver / controlled ────
out(`-- 5. medicine_pregnancy_warnings`);

// We need medicine_id per ingredient — link by matching generic_name
// lowercase. The safety engine does the same lookup. We assume
// ingredient == generic_name in our curated data; if we later add
// combo drugs the matcher needs to be expanded.
const masterIdByIngredient = new Map<string, string>();
for (const m of SEED_MEDICINES) {
  masterIdByIngredient.set(m.genericName.toLowerCase(), masterIdByRxcui.get(m.rxcui)!);
}

for (const w of SEED_PREGNANCY_WARNINGS) {
  const ingKey = w.ingredient.toLowerCase();
  const medicineId = masterIdByIngredient.get(ingKey);
  if (!medicineId) {
    // Not in the curated set — skip. Future enrichments can add these.
    continue;
  }
  const rowId = deterministicId(`preg:${medicineId}:${w.fdaCategory}:${w.severity}`);
  out(
    `INSERT OR REPLACE INTO medicine_pregnancy_warnings (id, medicine_id, fda_category, trimester, severity, notes) ` +
      `VALUES ('${rowId}', '${medicineId}', ${w.fdaCategory ? `'${esc(w.fdaCategory)}'` : "NULL"}, 'all', '${w.severity}', '${esc(w.notes)}');`
  );
}

out(``);
out(`-- 6. medicine_renal_adjustments`);
for (const r of SEED_RENAL_ADJUSTMENTS) {
  const ingKey = r.ingredient.toLowerCase();
  const medicineId = masterIdByIngredient.get(ingKey);
  if (!medicineId) continue;
  const rowId = deterministicId(`renal:${medicineId}:${r.egfrMin}:${r.egfrMax}`);
  out(
    `INSERT OR REPLACE INTO medicine_renal_adjustments (id, medicine_id, egfr_min, egfr_max, dose_adjustment, notes) ` +
      `VALUES ('${rowId}', '${medicineId}', ${r.egfrMin}, ${r.egfrMax}, '${esc(r.doseAdjustment)}', '${esc(r.notes)}');`
  );
}

out(``);
out(`-- 7. medicine_liver_adjustments`);
for (const l of SEED_LIVER_ADJUSTMENTS) {
  const ingKey = l.ingredient.toLowerCase();
  const medicineId = masterIdByIngredient.get(ingKey);
  if (!medicineId) continue;
  const rowId = deterministicId(`liver:${medicineId}:${l.childPugh}`);
  out(
    `INSERT OR REPLACE INTO medicine_liver_adjustments (id, medicine_id, child_pugh, dose_adjustment, notes) ` +
      `VALUES ('${rowId}', '${medicineId}', '${l.childPugh}', '${esc(l.doseAdjustment)}', '${esc(l.notes)}');`
  );
}

out(``);
out(`-- 8. medicine_controlled`);
for (const c of SEED_CONTROLLED) {
  const ingKey = c.ingredient.toLowerCase();
  const medicineId = masterIdByIngredient.get(ingKey);
  if (!medicineId) continue;
  const rowId = deterministicId(`controlled:${medicineId}:LK`);
  out(
    `INSERT INTO medicine_controlled (id, medicine_id, schedule, region, notes) ` +
      `VALUES ('${rowId}', '${medicineId}', '${esc(c.schedule)}', 'LK', '${esc(c.notes)}') ` +
      `ON CONFLICT(medicine_id, region) DO UPDATE SET ` +
      `schedule = excluded.schedule, notes = excluded.notes;`
  );
}

out(``);

// ─── Apply via wrangler ────────────────────────────────────
const tmp = mkdtempSync(join(tmpdir(), "seed-"));
const file = join(tmp, "seed-medicines.sql");
writeFileSync(file, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${lines.length} SQL lines to ${file}`);
console.log(`Seeding ${SEED_MEDICINES.length} medicines + ${SEED_INTERACTIONS.length} interactions + ${SEED_ALLERGY_FAMILIES.reduce((a, f) => a + f.members.length, 0)} allergy rows...`);

const isRemote = process.argv.includes("--remote");
const targetFlag = isRemote ? "--remote" : "--local";
console.log(`Targeting D1 database with flag: ${targetFlag}`);

const result = spawnSync(
  "wrangler",
  ["d1", "execute", "healthcare-db", targetFlag, "--file", file],
  { stdio: "inherit", cwd: process.cwd() }
);

if (result.status !== 0) {
  console.error(`wrangler exited with status ${result.status}`);
  process.exit(1);
}
console.log("Seed complete.");
